# Generated by Django 3.2.9 on 2022-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='component_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='coordinate_x',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='coordinate_y',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
