# Generated by Django 3.2.9 on 2022-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20220107_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_state',
            field=models.CharField(choices=[('PROCESSING', 'In_progress'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=10),
        ),
    ]
