# Generated by Django 3.2.9 on 2022-01-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_alter_job_job_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
