# Generated by Django 3.2.9 on 2022-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_delete_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='helpful',
            new_name='rework',
        ),
        migrations.RemoveField(
            model_name='error',
            name='component_name',
        ),
        migrations.AddField(
            model_name='error',
            name='component_value',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='cropped_panel_photo',
            field=models.ImageField(default=None, null=True, upload_to='data/cropped_panel_images/'),
        ),
    ]
